services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: converthub_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: converthub_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: converthub_mysql
    environment:
      MYSQL_DATABASE: converthub
      MYSQL_USER: converthub
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: converthub_redis
    ports:
      - "6379:6379"

  node:
    image: node:22-alpine
    container_name: converthub_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: converthub_queue
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: php artisan queue:work redis --queue=conversions,default --tries=3 --timeout=3600
    depends_on:
      - app
      - redis
      - mysql

volumes:
  mysql_data:

